### ISSUE TITLE
file location

### ISSUE THREAD

**Issue by rinzes** [haum/TwitterBot#28]
stupid question... were does one place the TwitterBot.pm file

**Comment by Matael** [comment]
Hi @rinzes, we decided not to create a fully compliant Perl module. Just drop the PM file in the same directory as your bot script.

**Comment by rinzes** [comment]
I'm getting the following errors:

./twitterbot.pl: line 1: use: command not found
./twitterbot.pl: line 4: syntax error near unexpected token `('
./twitterbot.pl: line 4: `my $Twaum = TwitterBot->new('

I thought the syntax error might be the editor however I redid it using a code one and still getting it. I'm not a code programmer so lost here.

**Comment by Matael** [comment]
The pl file doesn't have a Shebang (the line stating which interpreter it must use). Add:

    #!/bin/perl

at the beginning to use it as a standalone script.

The other (recommended) way to go is to call the script through perl itself:

    perl twitterbot.pl

**Comment by rinzes** [comment]
Thanks.. After resolving all the dependancy + Installing redis I get the following:

Your credentials do not allow access to this resource at /usr/local/share/perl/5.20.2/TwitterBot.pm line 339 at /usr/local/share/perl/5.20.2/Bot/BasicBot.pm line 535.

**Comment by Matael** [comment]
The error is self-explanatory: when issuing the credentials for the bot in its Twitter account, you must grant access both to read and write tweets.

**Comment by rinzes** [comment]
Thanks for your help. I didn't have the tokens installed and it now is connected to my irc channel but no tweets are being posted.

**Comment by Matael** [comment]
If you use the ``@tweet My tweet's text`` in your IRC channel and if your tokens have the correct permissions, the tweets should be posted. If not test the tokens using https://dev.twitter.com/rest/reference/post/statuses/update

**Comment by rinzes** [comment]
Well... I guess my understanding how this works is wrong. I thought that the tweets from people I follow would get reposted in the #channel. I did @tweet My tweet's text and that sent a text to my registered tweeter account and I replied and it showed up in my IRC channel however, none of the tweets from people I follow don't show up.in the #channel. What am I doing wrong

**Comment by Matael** [comment]
You didn't understand what the bot does. The program is supposed to output the tweets in which **you are mentioned** on the IRC channel (and not all the tweets from people you follow) and post on twitter the tweets input on IRC.

To you achieve what you want, take a look at [Bitlebee](https://www.bitlbee.org).
